### ISSUE TITLE
Telegram Bot gibt keine Rückmeldung

### ISSUE THREAD

**Issue by Cynexxde** [binsky08/openITCOCKPIT-Telegram-Module#1]
Guten Tag,
ich habe das Plugin wie angegeben installiert, jedoch ohne real-time interactions. Das Problem ist leider, dass der Befehl /auth und /start keine Rückmeldung des Bots zurückgibt. Sollte dies nicht der Fall sein? Gibt es irgendwo eine Log die ich mir anschauen kann?

**Comment by Cynexxde** [comment]
Ich habe selbstverständlich den Token mehrfach geprüft, die VM neu gestartet und auch mehrere Exports durchgeführt. 

Wenn ich die two-way webhook integration aktivieren/speichern möchte, dann erhalte ich folgende Meldung.
![image](https://user-images.githubusercontent.com/88704661/144705305-3e57ad0b-de04-4adc-bb12-91548f61a600.png)
An sich benötige ich diese aber nicht.


Mein Browser zeigt folgende Meldung an.
![image](https://user-images.githubusercontent.com/88704661/144705529-11a391af-3cb2-480a-9a15-cbe940c67995.png)

**Comment by binsky08** [comment]
hmm, das klingt für mich erst mal, als  wären die Tabellen nicht erstellt. Kannst du noch mal prüfen, ob das Snippet mit dem autoload in der /opt/openitc/frontend/src/Lib/PluginManager.php an der richtigen Stelle drin steht, danach ein openitcockpit-update ausführen und dessen Output etwas im Auge behalten ob es Fehler mit dem Plugin gibt.
Du könntest mal in der DB schauen, ob die Tabellen existieren.

Kommt der Error while saving data Fehler generell, oder nur wenn du die two-way webhook integration aktiviert hast und dann speichern möchtest?

Der 500 Error sollte (hoffentlich) hier drin stehen: /opt/openitc/logs/nginx/error.log

**Comment by Cynexxde** [comment]
Die Datei /opt/openitc/logs/nginx/error.log ist leer.

![image](https://user-images.githubusercontent.com/88704661/144991097-49ce391b-0278-4c13-86df-24c095eea6f0.png)
openitcockpit-update zeigt keine Fehler.


composer install zeigt die folgenden Fehler.

![image](https://user-images.githubusercontent.com/88704661/144992089-73b4ebbe-f12f-4bae-bd3e-6d78628ab5e3.png)

**Comment by binsky08** [comment]
das mit composer install ist so in Ordnung, da mit dem composer.lock file die Abhängigkeiten auf eine bestimmte (als funktionierend bekannte) Version gepinnt wurden.
Da die Datei PluginManager.php korrekt aussieht und openitcockpit-update ausgeführt wurde, kann ich nicht sagen, wo das Problem herkommt.

Wie gesagt, kontrolliere bitte mal in deiner Datenbank, ob eine Tabelle telegram_settings existiert. Diese sollte derzeit genau einen Datensatz enthalten. Falls es mehr sind, auf einen reduzieren, falls nichts drin steht ... hmm keine Ahnung (wüsste nicht, was sonst den Speichervorgang blockieren sollte).

Keine Ahnung ob das hilfreich ist, das Plugin sollte mit php7.2/7.3/7.4 funktionieren, php8.0 ist nicht getestet.

**Comment by Cynexxde** [comment]
![image](https://user-images.githubusercontent.com/88704661/145104692-42d2a732-5f6b-48cb-8de9-7de1f159a3cf.png)

![image](https://user-images.githubusercontent.com/88704661/145104901-22daf339-2512-4712-8698-238105b798e2.png)

**Comment by binsky08** [comment]
kann da keinen Fehler feststellen

**Comment by Cynexxde** [comment]
Ich probiere es am Wochenende bei einer anderen oitc Installation noch einmal aus. Ich gebe dann mal Feedback ^^

**Comment by Cynexxde** [comment]
Ich habe es gerade erneut installiert. Ohne Webhooks funktioniert es einfach nicht. Diese Konfiguration hiervon konnte ich nun jedoch vornehmen und die Autorisierung scheint auch geklappt zu haben.
![image](https://user-images.githubusercontent.com/88704661/145707381-3124c919-4580-4a75-beb4-c7f50e5fc607.png)

Ich habe die Host- und Servicekommandos hinzugefügt
![image](https://user-images.githubusercontent.com/88704661/145707403-1996a8d6-37c7-42cf-a2d2-76802ee275d1.png)

Die Kommandos werden auch ausgeführt.
![image](https://user-images.githubusercontent.com/88704661/145707422-97c4738c-c824-42c9-a1a6-e30fe371445f.png)

Doch leider erhalte ich keine Benachrichtigungen. Übersehe ich etwas?
Es handelt sich nun übrigens um ein komplett neu installiertes System mit Debian 10.

**Comment by Cynexxde** [comment]
Konntest du das Problem nachvollziehen bzw. taucht es bei dir auch auf? Kannst du mir in der nächsten Zeit weiterhelfen? Ich muss mich sonst nach einer anderen Möglichkeit umsehen.

**Comment by binsky08** [comment]
Hi Cynexxde, ich kann das Problem nicht nachvollziehen. Aus deinem Fehlerbild werde ich auch nicht mehr schlau.
Eventuell ein Firewall Problem?

> Konntest du das Problem nachvollziehen bzw. taucht es bei dir auch auf?

Das Telegram Modul läuft bei mir in produktiv bisher ohne Probleme.
In einer Neuinstallation konnte ich es bisher leider nicht testen, da die openitcockpit Installation auf einem Debian 10 bei mir fehlschlägt. (hab den devs schon Bescheid gegeben)
Edit: Fehler wurde behoben

> Kannst du mir in der nächsten Zeit weiterhelfen?

Wenn ich neben Studium und anderen Projekten Zeit finde helfe ich gerne wo ich kann.

**Comment by binsky08** [comment]
@Cynexxde, ich konnte das Problem möglicherweise identifizieren.
Wenn der Telegram Bot bereits einmal mit Webhooks genutzt wurde, kann dieser nachfolgend erst wieder im "One Way Modus" genutzt werden, wenn über die Telegram Settings im openITCOCKPIT die TwoWay Option wieder deaktiviert wurde.

Davon abgesehen funktioniert das Telegram Modul bei mir auf einer frischen Debian 10 Installation.

Weshalb der "Error while saving data" Error bei dir auftaucht ist mir jedoch nicht ganz klar.
Hast du das `composer install` im Ordner `/opt/openitc/frontend/plugins/TelegramModule` erfolgreich ausgeführt? (im Zweifelsfall einfach nochmal ausführen)

**Comment by binsky08** [comment]
@Cynexxde aktualisiere bitte mal das Modul bei dir. 
Ein `git pull` im Ordner `/opt/openitc/frontend/plugins/TelegramModule` sollte ausreichen.
Falls nicht zuvor schon geschehen, bitte sicherstellen, dass das oben beschriebene composer install geklappt hat.
Ich hoffe, dass das dein Problem löst. 

Sollte es Probleme mit Benachrichtigungen geben, lohnt sich ein Blick in die Logentries.
![image](https://user-images.githubusercontent.com/30630233/147615261-d7b273a0-a0c8-4991-b2b3-49110b05454b.png)

**Comment by Semetra22** [comment]
@binsky08 
Ich habe leider das selbe Problem.

Hier der Auszug aus dem Log:
 
`Undefined index: Command in /opt/openitc/frontend/plugins/TelegramModule/src/Controller/TelegramSettingsController.php on line 75
PHP Notice:  Trying to access array offset on value of type null in /opt/openitc/frontend/plugins/TelegramModule/src/Controller/TelegramSettingsController.php on line 75" while reading response header from upstream, client: 192.168.10.15, server: , request: "POST /telegram_module/TelegramSettings/index.json?angular=true HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm-oitc.sock:", host: "meine-domain.de", referrer: "https://meine-domain.de/"` 

Gibt es da einen Lösungsansatz? 
Danke für die Arbeit!

**Comment by binsky08** [comment]
Hallo @Semetra22, es scheint mir nicht unbedingt das selbe Problem zu sein. Aber mal schauen.
Eventuell gibt es da ein Problem beim Abfragen der Commands Tabelle, da scheinbar `null` als Antwort geliefert wird, dies dort aber eigentlich nicht zulässig ist.

Bitte beantworte mir folgende Fragen:

- Welche php Version und openITCOCKPIT Version nutzt du?

- Ist das Problem direkt nach einer Neuinstallation aufgetreten, oder nutzt du die Instanz schon länger?

- Hast du das `composer install` im Ordner `/opt/openitc/frontend/plugins/TelegramModule` erfolgreich ausgeführt? (im Zweifelsfall einfach nochmal ausführen)

- Wird `oitc migrations seed -p TelegramModule` korrekt aufgeführt? (wird eigentlich automatisch beim openitcockpit-update ausgeführt und stellt sicher, dass unter anderem die notification commands existieren)

**Comment by Semetra22** [comment]
Hey @binsky08 danke für die schnelle Antwort und deine Hilfe! 
Tatsächlich ist die Installation noch relativ neu. Es sind aber Host und Services vorhanden.

- `php Version: 
PHP 7.4.30;
Zend Engine v3.4.0;
Zend OPcache v7.4.30`

- Ein erneutes Ausführen von `composer install` liefert folgendes:

![image](https://user-images.githubusercontent.com/22130015/195535876-b1bd428f-8347-4e8a-9658-97d31e556648.png)

- Auch `oitc migrations seed -p TelegramModule` wird korrekt ausgeführt:

![image](https://user-images.githubusercontent.com/22130015/195536871-8d0d27d3-b64b-445d-b064-1fc4d4674371.png)

Versuche Ich den Webhook mit dem API-Key zu aktivieren bekomme Ich aber leider immernoch den Fehler.
Im `error.log`  steht folgendes:

>2022-10-13 09:58:42 error: [TelegramBot\Api\HttpException] Resolving timed out after 5000 milliseconds in /opt/openitc/frontend/plugins/TelegramModule/vendor/telegram-bot/api/src/BotApi.php on line 265
Request URL: /telegram_module/TelegramSettings/index.json?angular=true
Referer URL: https://openitcockpit.meinedomain.de/
Client IP: x.x.x.x

Nginx `error.log`  :

>2022/10/13 10:00:11 [error] 31662#31662: *1691 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: Command in /opt/openitc/frontend/plugins/TelegramModule/src/Controller/TelegramSettingsController.php on line 75PHP message: PHP Notice:  Trying to access array offset on value of type null in /opt/openitc/frontend/plugins/TelegramModule/src/Controller/TelegramSettingsController.php on line 75PHP message: PHP Notice:  Trying to access array offset on value of type null in /opt/openitc/frontend/plugins/TelegramModule/src/Controller/TelegramSettingsController.php on line 75" while reading response header from upstream, client: x.x.x.x, server: , request: "POST /telegram_module/TelegramSettings/index.json?angular=true HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm-oitc.sock:", host: "openitcockpit.heko-technik.de", referrer: "https://openitcockpit.meinedomain.de/"

Danke für die Unterstützung!
Vielleicht kann man dir mal einen Kaffee spendieren 😄

**Comment by binsky08** [comment]
Bin nicht sicher, was da genau versucht wird zu "resolven", aber ist `api.telegram.org` vom oitc erreichbar / kann aufgelöst werden?
Benutzt du im oitc eventuell einen Proxy? (der müsste dann entsprechend im Telegram Modul aktiviert werden)

Bitte aktualisiere mal deine Version des Moduls aus dem main Branch des Repos: https://github.com/binsky08/openITCOCKPIT-Telegram-Module#update
Hab da ein paar Kleinigkeiten gerade gezogen. Vielleicht hilft es ja :)
